### ISSUE TITLE
Move to yarn

### ISSUE THREAD

**Issue by buttonfreak** [meisterplayer/meister-woodstock-target-template#4]
Move to yarn instead of npm for much faster installing and less files

**Comment by FranklinWaller** [comment]
Or just use NPM 5: https://github.com/siddharthkp/npm-cache-benchmark with shrinkwrap: http://blog.npmjs.org/post/154473364440/npm5-specifications-and-our-rfc-process

**Comment by ivo-toby** [comment]
No.. YARN is out of the question
